# сначала требуется запустить Docker Desktop в качестве демона (просто с рабочего стола и выполнить вход в аккаунт)
version: "3" # файл docker-compose должен начинаться с тега версии (3 — новейшая версия на момент написания)

# docker-composes работает с сервисами, 1 сервис = 1 контейнер (сервисом может быть клиент, сервер, сервер баз данных...)
services: # раздел, в котором описаны сервисы
  kafka: # названием сервиса (контейнера), может быть любым
    hostname: 'kafka' # имя хоста для контейнера
    image: 'bitnami/kafka:latest' # image для докера (определяет, что будет поддерживать в докере)
    ports: # порты, с которыми будет работать сервис (для обращения к сервису за пределами контейнера с помощью перенаправления указанных портов на порт компьютера (не докера))
      # формат записи {порт компьютера}:{порт контейнера}
      - '9097:9097'
      - '9095:9095'
    environment: # переменные окружения для контейнера
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9097,CONTROLLER://:9093,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9097,EXTERNAL://localhost:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT